# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tricycle', '0005_driver_image'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='comment',
            field=models.TextField(max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tricycle.Driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
