# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20170817_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
