# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 08:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tricycle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='tricycle',
        ),
        migrations.AddField(
            model_name='tricycle',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tricycle.Driver'),
        ),
        migrations.AlterField(
            model_name='tricycle',
            name='body_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
