# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tricycle', '0002_auto_20170813_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(default='null', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operator',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
