# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tricycle', '0005_driver_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='contact_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operator',
            name='contact_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
